syntax = "proto3";

package stonfi.omni.v1beta8;

import "stonfi/omni/v1beta8/resolver/request.proto";
import "stonfi/omni/v1beta8/resolver/event.proto";

// Bidirectional streaming API used by resolvers to connect, receive events,
// and send protocol requests.
service ResolverRpc {
  // Connects the resolver to the protocol.
  //
  // Fatal errors (ex: authentication error) cause gRPC error & disconnect.
  // The server will return non-fatal errors in the form of events (ex:
  // QuoteRejectedEvent).
  //
  // The resolver must start communication by sending `ConnectRequest` to
  // authenticate itself.
  rpc Open(stream ResolverRequest) returns (stream ResolverEvent) {}
}
